---
apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
 name: tap-flask
spec:
 serviceAccountName: default # ServiceAccount on run cluster with permissions to deploy Package, see "Set up run Cluster Namespaces"
 packageRef:
   refName: tap-flask.dev.itq.lab # name of the Package
   versionSelection:
     constraints: 20240323125933.0.0+build.666be0c # version of the Package
 values:
 - secretRef:
     name:  tap-flask-values # Secret created in previous step
