apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: tap-flask.dev.itq.lab.20240323125203.0.0+build.666be0c
spec:
  refName: tap-flask.dev.itq.lab
  version: 20240323125203.0.0+build.666be0c
  releaseNotes: |
    Release v20240323125203.0.0+build.666be0c of package tap-flask.dev.itq.lab
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: harbor.tap.itq.lab/tap/workloads/tap-flask-dev-bundle@sha256:2ddbec0abcb13fdb9cea2a52856c904c5fbee365479a5c394c79a777c11f969a
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

