apiVersion: apis.apps.tanzu.vmware.com/v1alpha1
kind: APIDescriptor
metadata:
  name: tap-flask
  annotations:
    local-source-proxy.apps.tanzu.vmware.com: harbor.tap.itq.lab/tap-source/vscode:dev-tap-flask@sha256:f681e93afec137d26c1f8709774b3e72bc520d9456cbf7e9dedefbe8dee54bbf
    autoscaling.knative.dev/minScale: "1"
  labels:
    apis.apps.tanzu.vmware.com/register-api: "true"
    app.kubernetes.io/part-of: tap-flask
    apps.tanzu.vmware.com/has-tests: "true"
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/component: run
    carto.run/workload-name: tap-flask
spec:
  type: openapi
  description: A set of API endpoints to manage the resources within the petclinic app.
  system: pet-clinics
  owner: team-petclinic
  location:
    apiSpec:
      path: /openapi.json
    server:
      ref:
        apiVersion: serving.knative.dev/v1
        kind: Service
        name: tap-flask

